@url=http://localhost:3000/api/users
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjkxYzY3OTQ4MTI5MWQxZTJkYWZmOWQiLCJpYXQiOjE2NTM5NjkzODQsImV4cCI6MTY1Mzk3Mjk4NH0.7z1MQjlLZ2NAH19hIDQd_OvwLo_r0CqIZAMO74LWQUc
##### GET USERS - GET  #####
GET {{url}}/
x-token: {{token}}

##### CREATE USER - POST  #####
POST {{url}}/
Content-Type: application/json

{
  "name":"pointH3",
  "mail":"p@gmail.com",
  "password":"123"
}